"""Run FAQ baseline on a dataset previously generated by run_inference.py.

Usage:
    python run_baseline.py --data_dir ./data --release v1.0.0-er500-d4-pn0.22
"""

import argparse
import json
import os

import numpy as np
from omegaconf import OmegaConf

from loaders import get_data, siamese_loader
from toolbox.baselines import evaluate_faq_inits


def build_dataset_config(
    config: dict, noise: float | None, num_examples: int
) -> OmegaConf:
    """Build a minimal OmegaConf dataset config from the saved config.json."""
    ds = config["dataset"]
    return OmegaConf.create(
        {
            "type": ds.get("type", "synthetic"),
            "n_vertices": ds["n_vertices"],
            "generative_model": ds["generative_model"],
            "noise_model": ds["noise_model"],
            "edge_density": ds["edge_density"],
            "noise": noise if noise is not None else ds["noise"],
            "test": {"num_examples": num_examples},
        }
    )


def main():
    parser = argparse.ArgumentParser(
        description="Run FAQ baseline on cached dataset from run_inference.py."
    )
    parser.add_argument(
        "--release",
        required=True,
        help="GitHub release tag (to locate config.json in checkpoint_dir)",
    )
    parser.add_argument(
        "--noise",
        type=float,
        default=None,
        help="Override noise level (default: from config.json)",
    )
    parser.add_argument(
        "--num_examples",
        type=int,
        default=100,
        help="Number of test examples (default: 100)",
    )
    parser.add_argument(
        "--checkpoint_dir",
        default="./checkpoints",
        help="Directory with downloaded models (default: ./checkpoints)",
    )
    parser.add_argument(
        "--data_dir",
        default="./data",
        help="Directory with cached datasets (default: ./data)",
    )
    args = parser.parse_args()

    # Load config from the release's config.json
    config_path = os.path.join(args.checkpoint_dir, args.release, "config.json")
    with open(config_path) as f:
        config = json.load(f)
    cfg_data = build_dataset_config(config, args.noise, args.num_examples)
    noise_used = cfg_data.noise
    print(
        f"Dataset: {cfg_data.generative_model}, n={cfg_data.n_vertices}, "
        f"density={cfg_data.edge_density}, noise={noise_used}, "
        f"examples={args.num_examples}"
    )

    # Load cached test data (generated by run_inference.py)
    data_test = get_data(cfg_data, args.data_dir, split="test")
    test_loader = siamese_loader(data_test, batch_size=1, shuffle=False)

    # Run FAQ baselines with streaming output: FAQ(D_cx) vs FAQ(J) vs Max-nce.
    print("\nRunning FAQ baselines (D_cx init vs barycenter J init) ...")
    acc_dcx, acc_j, acc_proj = [], [], []
    nce_dcx, nce_j, nce_max, nce_planted = [], [], [], []
    sample_idx = 0

    for batch in test_loader:
        data1, data2, target = batch
        g1 = data1["input"][:, 0, :, :].cpu().detach().numpy()
        g2 = data2["input"][:, 0, :, :].cpu().detach().numpy()
        planted = target.cpu().detach().numpy()
        bs = planted.shape[0]

        for i in range(bs):
            sample_idx += 1
            pl = np.argmax(planted[i], 0) if planted[i].ndim == 2 else planted[i]
            r = evaluate_faq_inits(g1[i], g2[i], pl)
            acc_dcx.append(r["acc_dcx"])
            acc_j.append(r["acc_j"])
            acc_proj.append(r["acc_proj"])
            nce_dcx.append(r["nce_dcx"])
            nce_j.append(r["nce_j"])
            nce_max.append(r["nce_max"])
            nce_planted.append(r["nce_planted"])

            print(
                f"  [{sample_idx}/{args.num_examples}] "
                f"acc: D_cx={r['acc_dcx']:.4f} J={r['acc_j']:.4f} proj={r['acc_proj']:.4f} "
                f"| avg: D_cx={np.mean(acc_dcx):.4f} J={np.mean(acc_j):.4f}",
                flush=True,
            )

    print("\n" + "=" * 60)
    print("FAQ BASELINE RESULTS")
    print("=" * 60)
    print(f"Release:             {args.release}")
    print(f"Noise:               {noise_used}")
    print(f"Test examples:       {sample_idx}")
    print("-" * 60)
    print(f"Acc  FAQ(D_cx):      {np.mean(acc_dcx):.4f}")
    print(f"Acc  FAQ(J):         {np.mean(acc_j):.4f}")
    print(f"Acc  D_cx projection:{np.mean(acc_proj):.4f}")
    print("-" * 60)
    print(f"NCE  FAQ(D_cx):      {np.mean(nce_dcx):.1f}")
    print(f"NCE  FAQ(J):         {np.mean(nce_j):.1f}")
    print(f"NCE  Max (true perm):{np.mean(nce_max):.1f}")
    print(f"NCE  planted:        {np.mean(nce_planted):.1f}")
    print("=" * 60)


if __name__ == "__main__":
    main()
