"""Run FAQ baseline on a dataset previously generated by run_inference.py.

Usage:
    python run_baseline.py --data_dir ./data --release v1.0.0-er500-d4-pn0.22
"""

import argparse
import json
import os

import numpy as np
from omegaconf import OmegaConf
from scipy.optimize import quadratic_assignment

from loaders import get_data, siamese_loader
from toolbox.baselines import relaxed_normAPPB_FW_seeds
from toolbox.utils import perm2mat


def build_dataset_config(
    config: dict, noise: float | None, num_examples: int
) -> OmegaConf:
    """Build a minimal OmegaConf dataset config from the saved config.json."""
    ds = config["dataset"]
    return OmegaConf.create(
        {
            "type": ds.get("type", "synthetic"),
            "n_vertices": ds["n_vertices"],
            "generative_model": ds["generative_model"],
            "noise_model": ds["noise_model"],
            "edge_density": ds["edge_density"],
            "noise": noise if noise is not None else ds["noise"],
            "test": {"num_examples": num_examples},
        }
    )


def main():
    parser = argparse.ArgumentParser(
        description="Run FAQ baseline on cached dataset from run_inference.py."
    )
    parser.add_argument(
        "--release",
        required=True,
        help="GitHub release tag (to locate config.json in checkpoint_dir)",
    )
    parser.add_argument(
        "--noise",
        type=float,
        default=None,
        help="Override noise level (default: from config.json)",
    )
    parser.add_argument(
        "--num_examples",
        type=int,
        default=100,
        help="Number of test examples (default: 100)",
    )
    parser.add_argument(
        "--checkpoint_dir",
        default="./checkpoints",
        help="Directory with downloaded models (default: ./checkpoints)",
    )
    parser.add_argument(
        "--data_dir",
        default="./data",
        help="Directory with cached datasets (default: ./data)",
    )
    args = parser.parse_args()

    # Load config from the release's config.json
    config_path = os.path.join(args.checkpoint_dir, args.release, "config.json")
    with open(config_path) as f:
        config = json.load(f)
    cfg_data = build_dataset_config(config, args.noise, args.num_examples)
    noise_used = cfg_data.noise
    print(
        f"Dataset: {cfg_data.generative_model}, n={cfg_data.n_vertices}, "
        f"density={cfg_data.edge_density}, noise={noise_used}, "
        f"examples={args.num_examples}"
    )

    # Load cached test data (generated by run_inference.py)
    data_test = get_data(cfg_data, args.data_dir, split="test")
    test_loader = siamese_loader(data_test, batch_size=1, shuffle=False)

    # Run FAQ baseline with streaming output
    print("\nRunning FAQ baseline (Frank-Wolfe + FAQ) ...")
    all_acc = []
    all_accd = []
    all_qap = []
    all_planted = []
    sample_idx = 0

    for batch in test_loader:
        data1, data2, target = batch
        g1 = data1["input"][:, 0, :, :].cpu().detach().numpy()
        g2 = data2["input"][:, 0, :, :].cpu().detach().numpy()
        planted = target.cpu().detach().numpy()
        n = planted.shape[-1]
        bs = planted.shape[0]

        for i in range(bs):
            sample_idx += 1
            if planted[i].ndim == 2:
                pl = np.argmax(planted[i], 0)
            P, col, _ = relaxed_normAPPB_FW_seeds(g1[i], g2[i])
            Pp = perm2mat(col)
            res_qap = quadratic_assignment(
                g2[i], -g1[i], method="faq", options={"P0": P, "maxiter": 30}
            )
            acc_faq = np.sum(pl == res_qap["col_ind"]) / n
            acc_proj = np.sum(pl == col) / n
            qap_score = (g2[i] * g1[i][res_qap["col_ind"], :][:, res_qap["col_ind"]]).sum() / 2
            planted_score = (g2[i] * g1[i][pl, :][:, pl]).sum() / 2

            all_acc.append(acc_faq)
            all_accd.append(acc_proj)
            all_qap.append(qap_score)
            all_planted.append(planted_score)

            print(
                f"  [{sample_idx}/{args.num_examples}] "
                f"acc_faq={acc_faq:.4f}  acc_proj={acc_proj:.4f}  "
                f"| running avg: acc_faq={np.mean(all_acc):.4f}  acc_proj={np.mean(all_accd):.4f}",
                flush=True,
            )

    all_acc = np.array(all_acc)
    all_accd = np.array(all_accd)
    all_qap = np.array(all_qap)
    all_planted = np.array(all_planted)

    print("\n" + "=" * 60)
    print("FAQ BASELINE RESULTS")
    print("=" * 60)
    print(f"Release:          {args.release}")
    print(f"Noise:            {noise_used}")
    print(f"Test examples:    {args.num_examples}")
    print(f"Acc (FAQ):        {all_acc.mean():.4f}")
    print(f"Acc (projection): {all_accd.mean():.4f}")
    print(f"QAP score (FAQ):  {all_qap.mean():.4f}")
    print(f"Planted score:    {all_planted.mean():.4f}")
    print("=" * 60)


if __name__ == "__main__":
    main()
